# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_all_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='binary_checksum',
            field=models.CharField(max_length=256),
        ),
    ]
