# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_all_analysis', '0003_analysis_curr_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='binary_name',
            new_name='project_name',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='curr_project_name',
        ),
    ]
