# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_all_analysis', '0004_auto_20170531_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='project_name',
            new_name='binary_name',
        ),
    ]
